"""aamasWeb URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin
from aamas import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^venue/', views.venue, name='venue'),
    url(r'^home/', views.home, name='home'),
    url(r'^submissions/', views.submissions, name='submissions'),
    url(r'^about/', views.about, name='about'),
    url(r'^callForPapers/', views.callForPapers, name='callForPapers'),
    url(r'^committees/', views.committees, name='committees'),
    url(r'^doctorMentor/', views.doctorMentor, name='doctorMentor'),
    url(r'^specialIndustrial/', views.specialInd, name='specialIndustrial'),
    url(r'^tourism/', views.tourism, name='tourism'),
    url(r'^tutorials/', views.tutorials, name='tutorials'),
    url(r'^workshops/', views.workshops, name='workshops'),
    url(r'^importantDates/', views.importantDates, name='importantDates'),
    url(r'^attendingAamas/', views.attendingAamas, name='attendingAamas'),
    url(r'^sponsors/', views.sponsors, name='sponsors'),
    url(r'^sponsorshipLevels/', views.sponsorshipLevels, name='sponsorshipLevels'),
    url(r'^blueSkyIdeasTrack/', views.blueSkyIdeasTrack, name='blueSkyIdeasTrack'),
    url(r'^roboticsTrack/', views.roboticsTrack, name='roboticsTrack'),
    url(r'^sociallyInteractiveAgentsTrack/', views.sociallyInteractiveAgentsTrack, name='sociallyInteractiveAgentsTrack'),
    url(r'^jaamasTrack/', views.jaamasTrack, name='jaamasTrack'),
    url(r'^localOrganization/', views.localOrganization, name='jaamasTrack'),
    url(r'^pc/', views.pc, name='jaamasTrack'),
    url(r'^spc/', views.spc, name='jaamasTrack'),
    url(r'^areaChairs/', views.areaChairs, name='areaChairs'),
    url(r'^callForTutorials/', views.callForTutorials, name='callForTutorials'),
    url(r'^callForDemos/', views.callForDemos, name='callForDemos'),
    url(r'^studentTravel/', views.studentTravel, name='studentTravel'),
    url(r'^accommodation/', views.accommodation, name='accommodation'),
    url(r'^additionalInfo/', views.additionalInfo, name='additionalInfo'),
    url(r'^stockholm/', views.stockholm, name='stockholm'),
    url(r'^traveling/', views.traveling, name='traveling'),
    url(r'^map/', views.map, name='map'),
    url(r'^acmSigai/', views.acmSigai, name='acmSigai'),
    url(r'^victorLesser/', views.victorLesser, name='victorLesser'),
    url(r'^exhibits/', views.exhibits, name='exhibits'),
    url(r'^ifaamasBestPaper/', views.ifaamasBestPaper, name='ifaamas'),
    url(r'^acceptedPapers/', views.acceptedPapers, name='acceptedPapers'),
    url(r'^acceptedPapers/', views.acceptedPapers, name='acceptedPapers'),
    url(r'^acceptedIndustrial/', views.acceptedPapersIndustrial, name='acceptedIndustrial'),
    url(r'^acceptedSIA/', views.acceptedPapersSIA, name='acceptedSIA'),
    url(r'^acceptedRobotics/', views.acceptedPapersRobotics, name='acceptedRobotics'),
    url(r'^acceptedBlueSky/', views.acceptedPapersBlueSky, name='acceptedBlueSky'),
    url(r'^workshopsList/', views.workshopsList, name='workshopsList'),
    url(r'^tutorialsList/', views.tutorialsList, name='workshopsList'),
    url(r'^invitedSpeakers/', views.invitedSpeakers, name='workshopsList'),
    url(r'^registration', views.registration, name='workshopsList'),
    url(r'^schedule', views.schedule, name='schedule'),
    url(r'^acceptedDoctoral', views.acceptedDoctoral, name='schedule'),
    url(r'^jul11', views.jul11, name='schedule'),
    url(r'^jul12', views.jul12, name='schedule'),
    url(r'^jul13', views.jul13, name='schedule'),
    url(r'^posterSchedule', views.posterSchedule, name='schedule'),
    url(r'^detailedProgram', views.detailedProgram, name='schedule'),
    url(r'^demoSchedule', views.demoSchedule, name='schedule'),
    url(r'^paperAward', views.paperAward, name='schedule'),
    url(r'^infoLast', views.infoLast, name='schedule'),
    url(r'^socialEvents', views.socialEvents, name='schedule'),
    url(r'^awardWinners', views.awardWinner, name='schedule'),

    #added to debug on local machine
    url(r'^aamas18/admin/', include(admin.site.urls)),
    url(r'^aamas18/venue/', views.venue, name='venue'),
    url(r'^aamas18/home/', views.home, name='home'),
    url(r'^aamas18/submissions/', views.submissions, name='submissions'),
    url(r'^aamas18/about/', views.about, name='about'),
    url(r'^aamas18/callForPapers/', views.callForPapers, name='callForPapers'),
    url(r'^aamas18/committees/', views.committees, name='committees'),
    url(r'^aamas18/doctorMentor/', views.doctorMentor, name='doctorMentor'),
    url(r'^aamas18/specialIndustrial/', views.specialInd, name='specialIndustrial'),
    url(r'^aamas18/tourism/', views.tourism, name='tourism'),
    url(r'^aamas18/tutorials/', views.tutorials, name='tutorials'),
    url(r'^aamas18/workshops/', views.workshops, name='workshops'),
    url(r'^aamas18/importantDates/', views.importantDates, name='importantDates'),
    url(r'^aamas18/attendingAamas/', views.attendingAamas, name='attendingAamas'),
    url(r'^aamas18/sponsors/', views.sponsors, name='sponsors'),
    url(r'^aamas18/sponsorshipLevels/', views.sponsorshipLevels, name='sponsorshipLevels'),
    url(r'^aamas18/blueSkyIdeasTrack/', views.blueSkyIdeasTrack, name='blueSkyIdeasTrack'),
    url(r'^aamas18/roboticsTrack/', views.roboticsTrack, name='roboticsTrack'),
    url(r'^aamas18/sociallyInteractiveAgentsTrack/', views.sociallyInteractiveAgentsTrack, name='sociallyInteractiveAgentsTrack'),
    url(r'^aamas18/jaamasTrack/', views.jaamasTrack, name='jaamasTrack'),
    url(r'^aamas18/localOrganization/', views.localOrganization, name='localOrganization'),
    url(r'^aamas18/pc/', views.pc, name='pc'),
    url(r'^aamas18/spc/', views.spc, name='areaChairs'),
    url(r'^aamas18/areaChairs/', views.areaChairs, name='jaamasTrack'),
    url(r'^aamas18/callForTutorials/', views.callForTutorials, name='callForTutorials'),
    url(r'^aamas18/callForDemos/', views.callForDemos, name='callForDemos'),
    url(r'^aamas18/studentTravel/', views.studentTravel, name='studentTravel'),
    url(r'^aamas18/accommodation/', views.accommodation, name='accommodation'),
    url(r'^aamas18/additionalInfo/', views.additionalInfo, name='additionalInfo'),
    url(r'^aamas18/stockholm/', views.stockholm, name='stockholm'),
    url(r'^aamas18/traveling/', views.traveling, name='traveling'),
    url(r'^aamas18/map/', views.map, name='map'),
    url(r'^aamas18/acmSigai/', views.acmSigai, name='acmSigai'),
    url(r'^aamas18/victorLesser/', views.victorLesser, name='victorLesser'),
    url(r'^aamas18/exhibits/', views.exhibits, name='exhibits'),
    url(r'^aamas18/ifaamasBestPaper/', views.ifaamasBestPaper, name='ifaamas'),
    url(r'^aamas18/acceptedPapers/', views.acceptedPapers, name='acceptedPapers'),
    url(r'^aamas18/acceptedIndustrial/', views.acceptedPapersIndustrial, name='acceptedIndustrial'),
    url(r'^aamas18/acceptedSIA/', views.acceptedPapersSIA, name='acceptedSIA'),
    url(r'^aamas18/acceptedRobotics/', views.acceptedPapersRobotics, name='acceptedRobotics'),
    url(r'^aamas18/acceptedBlueSky/', views.acceptedPapersBlueSky, name='acceptedBlueSky'),
    url(r'^aamas18/workshopsList/', views.workshopsList, name='workshopsList'),
    # url(r'^scrollingnavbar/', views.scrollingnavbar, name='about'),
    url(r'^aamas18/tutorialsList/', views.tutorialsList, name='workshopsList'),
    url(r'^aamas18/invitedSpeakers/', views.invitedSpeakers, name='workshopsList'),
    url(r'^aamas18/registration', views.registration, name='workshopsList'),
    url(r'^aamas18/schedule', views.schedule, name='schedule'),
    url(r'^$', views.home),
    url(r'^aamas18/acceptedDoctoral', views.acceptedDoctoral, name='schedule'),
    url(r'^aamas18/jul11', views.jul11, name='schedule'),
    url(r'^aamas18/jul12', views.jul12, name='schedule'),
    url(r'^aamas18/jul13', views.jul13, name='schedule'),
    url(r'^aamas18/posterSchedule', views.posterSchedule, name='schedule'),
    url(r'^aamas18/detailedProgram', views.detailedProgram, name='schedule'),
    url(r'^aamas18/demoSchedule', views.demoSchedule, name='schedule'),
    url(r'^aamas18/paperAward', views.paperAward, name='schedule'),
    url(r'^aamas18/infoLast', views.infoLast, name='schedule'),
    url(r'^aamas18/socialEvents', views.socialEvents, name='schedule'),
    url(r'^aamas18/awardWinners', views.awardWinner, name='schedule'),
]


